In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"D:\Machine Learning\loan_data.csv")

In [4]:
df

   Income  Credit_Score Loan_Status
0   25000           500    Rejected
1   30000           550    Rejected
2   35000           580    Rejected
3   40000           620    Approved
4   45000           650    Approved
5   50000           700    Approved
6   55000           730    Approved
7   60000           760    Approved
8   28000           520    Rejected
9   47000           680    Approved

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Loan_Status"] = le.fit_transform(df["Loan_Status"])

In [11]:
df

   Income  Credit_Score  Loan_Status
0   25000           500            1
1   30000           550            1
2   35000           580            1
3   40000           620            0
4   45000           650            0
5   50000           700            0
6   55000           730            0
7   60000           760            0
8   28000           520            1
9   47000           680            0

In [12]:
x = df.drop(columns=["Loan_Status"])
y = df["Loan_Status"]

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y,
test_size=0.2, random_state=42)

In [16]:
from sklearn.svm import SVC
model = SVC(kernel="linear")
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred

array([1, 1])

In [17]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
accuracy

1.0